// Generated by Wrangler by running `wrangler types --experimental-include-runtime
import type { KVNamespace } from '@cloudflare/workers-types';

interface Env {
	"spelltable-spelltable": KVNamespace;
	DISCORD_TOKEN: string;
	DISCORD_APPLICATION_ID: string;
	DISCORD_PUBLIC_KEY: string;
	DISCORD_TEST_GUILD_ID: string;
	client_id: string;
	client_secret: string;
}
