name = "spelltable"
main = "src/worker.js"
compatibility_date = "2024-12-09"
workers_dev = true
# node_compat = true

kv_namespaces = [
	{ binding = "spelltable-spelltable", id = "ebd4e4fb5b5842e8be52161b332a03f6" },
]

[vars]
PRINTER_ENABLED = true
